### PR TITLE
Make: update the cert fingerprint for dylib signing

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

https://github.com/calabash/calabash-codesign/pull/8

### CODE REVIEW

**Comment by jmoody** [comment]
ATTN @sapieneptus 

This might fail.  There was an unexpected UI dialog when I ran some local tests.

If it passes.  Please merge.

**Comment by sapieneptus** [comment]
Alright, I'll await results. You mean it prompted you for a password when you did it locally (access to keychain password prompt) ? I would think CI has some workaround for that.

**Comment by jmoody** [comment]
> CI workaround

This _is_ the CI workaround. The whole process should not require a username password.

**Comment by sapieneptus** [comment]
huzzah!

**Pull request merged**
