### PR TITLE
Version tool: turn off legacy coverage build option

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

Users are still reporting spam from the `version` tool.

* version tool is generating "cannot find gcda" output #289

ATTN: @kaorijp Thanks for reporting.

### To Review

1. Download: https://www.dropbox.com/s/vky6xh9vjcgyj54/calabash.framework.tar.xz?dl=0
2. Expand - can be done in the Finder or with `tar -xf`.

```
# There should be no other output
$ calabash.framework/Resources/version
0.17.0
```

### CODE REVIEW

**Comment by kaorijp** [comment]
Thanks dear friend !
I will confirm asap

**Comment by jmoody** [comment]
@kaorijp I added instructions for reviewing.  Thanks.

**Comment by sapieneptus** [comment]
Dumb question, but why did CI fail there?

**Comment by jmoody** [comment]
Not a dumb question.  The Details link will take you to the build.

The cucumbers are failing because of:

```
15:01:50 Failing Scenarios:
15:01:50 cucumber -p simulator -p app -p common -p ss_path -p html_report features/shake.feature:5 # Scenario: Shake the device
```

I just noticed this while testing locally and on the XTC:

* https://testcloud.xamarin.com/test/45829ca8-00de-40f4-9820-33bfdd2ee06f/

The shake route is not working.  The app crashes with:

```
Dec 21 15:38:22 stern backboardd[60381]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec 21 15:38:22 stern backboardd[60381]: SecTaskCopyDebugDescription: LPTestTarget[60440]
Dec 21 15:38:22 stern backboardd[60381]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec 21 15:38:22 stern backboardd[60381]: SecTaskCopyDebugDescription: LPTestTarget[60440]
Dec 21 15:38:22 stern backboardd[60381]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec 21 15:38:22 stern backboardd[60381]: SecTaskCopyDebugDescription: LPTestTarget[60440]
Dec 21 15:38:22 stern backboardd[60381]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec 21 15:38:22 stern backboardd[60381]: SecTaskCopyDebugDescription: LPTestTarget[60440]
Dec 21 15:38:22 stern backboardd[60381]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec 21 15:38:22 stern backboardd[60381]: SecTaskCopyDebugDescription: LPTestTarget[60440]
```

**Comment by jmoody** [comment]
@sapieneptus In cases like this, where the failing CI is because an unrelated issue, I am content to merge as long as I capture the problem in an issue.  Let me know if you feel otherwise.

**`shake` is causing app crashes on certain Xcode and iOS combinations** [#968](https://github.com/calabash/calabash-ios/issues/968)

**Comment by sapieneptus** [comment]
Gotcha, looks good to me

**Comment by sapieneptus** [comment]
whoops

**Comment by kaorijp** [comment]
Hi @jmoody 
Sorry for late reply . 
I have already confirmed the fixed version of calabash framework. 
It's working as expected :+1: 
Thank you so much !

>P-AD:project booby$ calabash.framework/Resources/version 
0.17.0

>xcrun strings MyApp.app/MyApp | grep -E 'CALABASH VERSION'
CALABASH VERSION: 0.17.0
CALABASH VERSION: 0.17.0  

In addition, could you please teach me how to reset app between scenario on REAL DEVICE and .APP file ( not .ipa file using)
Because, I have tried your way in URL : http://stackoverflow.com/questions/24493634/reset-ios-app-in-calabash-ios  
-> I'm not using .ipa file to install. 
I'm using .app file ( How to custom your file to adapt .app file install ? )
・Uninstall : ideviceinstaller -U <bundleID of APP>
・Install     : ideviceinstaller -i Myapp.app

**Comment by sapieneptus** [comment]
Hi @kaorijp,

If I am understanding you correctly, you are trying to install a simulator bundle onto a physical device? `.app` files are usually only for simulator (you can confirm by checking the architectures with `file ./<appname>.app/<appname>` - architectures like i386 are for simulator only). 

If it's a simulator app, then `ideviceinstaller` will not work - you'd have to use `simctl`. @jmoody would know more.

**Comment by kaorijp** [comment]
Hi @sapieneptus 
Thank for your reply.

I'm running calabash on Physical device -> Of course I have to build .app file to adapt real device. 
I would like to explain in detail. 
I have a lot of feature/scenario. Everything is working now. Testing on Real Device ( iPhone6)
However , only some login feature which is testing for login account, login status v.v.v. that I have reset app before scenario to make sure it does not store the login information. 
-> Because of can not reset app in Real Device ( Simulator is OK ) that I must separate 2 command:  
1. Without RESET_BETWEEN_SCENARIOS = 1
2. Add option RESET_BETWEEN_SCENARIOS = 1 when run cucumber -v

 http://stackoverflow.com/questions/24493634/reset-ios-app-in-calabash-ios
Above of this link, @jmoody has just impl in case of install by IPA. I want to custom for .APP also

**Comment by jmoody** [comment]
I will be on vacation until Jan 4.

**Comment by sapieneptus** [comment]
@kaorijp 

In the absence of @jmoody's wisdom, the obvious thing that comes to mind is this: why not wrap the `.app` into a `.ipa`?

```shell
mkdir Payload
mv <appname>.app Payload
zip -q <appname>.ipa Payload
```

If that doesn't work for you, maybe you could point out exactly which part requires an .ipa here -> http://stackoverflow.com/questions/24493634/reset-ios-app-in-calabash-ios ?

**Comment by kaorijp** [comment]
Hi @sapieneptus 

I also confirmed .ipa file before, because some of below problem that I do not want to use .ipa to test calabash. 
Beside that, .app is working find. 
Can you have a look at on below error ?

>P-AD:project booby$ ideviceinstaller -i Myapp.ipa
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/Myapp.appInfo.plist in archive!

**Comment by jmoody** [comment]
@kaorijp 

That output is normal for `ideviceinstaller`.  It is safe to ignore.

**Comment by kaorijp** [comment]
@jmoody
Oh. Really.
Thank you so much and Happy new year !

**Pull request merged**
