### PR TITLE
Detect legacy apps and used the scaleFactor for iPhone 6 Plus devices

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

Resolves:

* [Jira: app.Tap is not working as expected on iPhone 6 Plus devices](https://xamarin.atlassian.net/browse/TCFW-37)

### Testing

See the [features/acquaint.feature](https://github.com/calabash/calabash-ios-server/blob/693528ed4c5cef67c1710c58c42cca3b2df46784/cucumber/features/acquaint.feature) for details about how to test on physical devices and simulators.

```
$ cd cucumber
$ bundle update
# Simulator
$ be cucumber -t @acquaint

# XTC
$ ./xtc-submit-acquaint
```

* [XTC](https://testcloud.xamarin.com/test/com-xamarin-acquaint-native_f29e20bb-a28c-44fa-a46f-0455e94c3087/)

### CODE REVIEW

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
Jenkins retest this please

**Comment by jmoody** [comment]
abeb84d is outside the scope of this PR but was included to trigger Jenkins CI.  WTB a reliable pull-request builder for Jenkins.

**Comment by jmoody** [comment]
@sapieneptus 

The only non-test related commit is this: b35c590

I am not sure if you can doing a meaningful review, but I am trying not to merge my own PRs.

**Comment by krukow** [comment]
@jmoody looks good to me, the only comment (non-blocking) is: it would be nice with a comment or description of the trial and error process used to derive the factor

**Comment by jmoody** [comment]
I tried to do some maths given the bag of information I had:  screen size for mode, screen height, screen size, and the scale values. That got me to a value of 1.5 which worked in some cases, but was clearly too large - touches would be below the center point of the view.

I went back to the original implementation (Oct 2015) to see if I had made a mistake refactoring (missing edge case?) and for inspiration.

**Comment by jmoody** [comment]
^ continued

I found no mistake and no inspiration.

I decided to go back to the [original Paint Code](http://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions) reference we used for the original scaling but found no new information.

The [Fingertips](https://github.com/mapbox/Fingertips) has been very helpful to visually debug touches so I added that behavior to the AcquaintNativeiOS app.  I tried touching on the details disclosure button in the table view rows - this is how I arrived at 1.3. This was good enough for a visual test, but not an automated test because the entire table view row is touchable.  For an automated test, I needed a small button (2x2) to touch - like in the [iPhoneOnly](https://github.com/calabash/ios-iphone-only-app) test app.

**Pull request merged**
