### PR TITLE
Add support for OpenGL views in LPScreenshotRoute

### PR DESCRIPTION
**Pull request by gKamelo**
Usage of latest UIKit API to capture more complex views like OpenGL, it could be helpful for MapKit or SpriteKit  views.

### CODE REVIEW

**Comment by jmoody** [comment]
@gKamelo Thanks for the pull request. Do you have any side-by-side screenshot comparisons?

@krukow My screenshot fu is very weak.  I am thinking this needs to be a different route?

See **screenshot route should use drawViewHierarchyInRect:afterScreenUpdates: for iOS 7** [calabash-ios #347](https://github.com/calabash/calabash-ios/issues/347)

**Comment by gKamelo** [comment]
@jmoody I've made quick comparison for SpriteKit scene, on left old version using `renderInContext:`, on right latest api `drawViewHierarchyInRect:afterScreenUpdates` method.
spritekit_comparision

Aside of this request, I found quite useful to capture screenshots via UIAutomation methods, but unfortunately it saves them after instruments finish.

**Comment by jmoody** [comment]
@gKamelo I think this needs to be a new screenshot route.

Any chance you'd be up for writing one?  If you want to get started, we can collaborate on a PR if you make a me collaborator on your fork.

**Comment by gKamelo** [comment]
@jmoody I would love to add this, but going to vacations right now. When i get back we could collaborate on this, it should be mid of 12th week.

**Comment by jonaswisplinghoff** [comment]
Any news on this @gKamelo @jmoody ? I'd really appreciate better screenshots.

**Comment by gKamelo** [comment]
@jonaswisplinghoff I should finally find time to work on this in the next days, in meantime as a temporary solution i would suggest to swizzle screenshot method via LPScreenshotRoute private class and add latest api solution.

**Comment by jmoody** [comment]
This definitely needs to be a separate screenshot route.  I've reviewed the relevant issues.  @gKamelo I am on vacation for 2 weeks starting Mon Apr 13.  I am still up for collaborating on a new screenshot route.  On the client side, we can provide a way to switch between screenshot routes.

**Comment by gKamelo** [comment]
@jmoody I've added you to my fork, so if you have time to help me starting/showing the way i would appreciate this.

**Comment by jmoody** [comment]
Cool beans.  I *might* get to this before I leave for vacation.

**Comment by jmoody** [comment]
@gKamelo 

How would you feel about starting over on a new branch?

This one is ~170 commits behind.  I want to add some files to this branch and I am worried about merge conflicts in the xcode project.

I can push a new branch to your fork and get you started on the new screenshot route.

**Comment by gKamelo** [comment]
@jmoody 

Sure, feel free to do that. I was thinking about closing this request and start over from clean state.

**Pull request closed without merging**
