### PR TITLE
remove log redirect

### PR DESCRIPTION
**Pull request by AlexWellsHS**
https://github.com/calabash/calabash-ios/issues/1386

### CODE REVIEW

**Comment by AlexWellsHS** [comment]
related to: https://github.com/calabash/DeviceAgent.iOS/pull/285

**Comment by jmoody** [comment]
@AlexWellsHS You need to sign the CLA before I can merge this pull request.

**Comment by jmoody** [comment]
Jenkins test this please.

**Comment by jmoody** [comment]
Jenkins test this please.

**Comment by AlexWellsHS** [comment]
@jmoody looks like the local tests failed http://calabash-ci.xyz:8081/blue/organizations/jenkins/calabash-ios-server/detail/PR-426/1/pipeline

**Pull request merged**
