### PR TITLE
Modified scrolling behaviour

### PR DESCRIPTION
**Pull request by idcuesta**
Changes include:
- Modified scrolling behaviour
- Added unit tests to cover the changes

### CODE REVIEW

**Comment by idcuesta** [comment]
This PR is a cleanup from the one over master branch -> https://github.com/calabash/calabash-ios-server/pull/45

Apologies for all the mess :(

**Comment by jmoody** [comment]
Hurray! @idcuesta FTW!

**Comment by jmoody** [comment]
@idcuesta Any chance you looked at an example that uses "pull down to refresh?"

I wonder if we have broken something here.  We don't have any examples.

**Comment by idcuesta** [comment]
@jmoody I didn't try pull to refresh, by in my previous experience scrolling up was not triggering pull to refresh action anyway.

I'm now working in a sample app with a table view with refresh control, I could give it a try

**Comment by jmoody** [comment]
@idcuesta 

> I'm now working in a sample app with a table view with refresh control, I could give it a try

That would be great.

FYI/BTW I am not going to delay the 0.13.0 for this.  The part of my brain that worries about breaking backward compatibility kicked in when I was writing the release notes.

**Pull request merged**
